name: build dotnet idk

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@latest
      name: checkout code
      
    - name: setup msbuild
      uses: microsoft/setup-msbuild@latest
      
    - name: setup nugget
      uses: nuget/setup-nuget@latest
      
    - name: restore nugget packages
      run: nuget restore TestCSharp.sln
      
    - name: Hey! Build the things
      run: msbuild TestCSharp.sln
