name: build dotnet idk

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      name: checkout code
      
    - name: setup msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: setup nugget
      uses: NuGet/setup-nuget@v1.0.2
      
    - name: restore nugget packages
      run: nuget restore TestCSharp.sln
      
    - name: Hey! Build the things
      run: msbuild TestCSharp.sln
