name: Download game

on: workflow_dispatch

jobs:
  download:
  
    runs-on: windows-latest
  
    steps:
      - name: Download Steam game
        uses: t0stiman/steam-download@main
        with:
          username: ${{ secrets.STEAM_USER }}
          password: ${{ secrets.STEAM_PASS }}
          totp: ${{ secrets.STEAM_TOTP }}
          appid: 428430
          filelist: splash.png,screenshot.txt
        
