name: Download game

on: workflow_dispatch

jobs:
  download:
  
    runs-on: windows-latest
  
    steps:
      - name: Download Steam game
        uses: dhkatz/steam-download@v1.2.0
        with:
          username: ${{ secrets.STEAM_USER }}
          password: ${{ secrets.STEAM_PASS }}
          totp: ${{ secrets.STEAM_TOTP }}
          appid: 428430
          # path: 
        
